# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  init:
    uses: ./.github/workflows/common-setup.yml

  build:  
    runs-on: ubuntu-latest
    needs: init
    steps:  

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
